scrollbar_interactive yes
scrollbar_width 0.8
cursor_trail 0


font_family      JetBrains Mono
font_size        10.0
background_opacity 0.98
background #1a1a1a

url_color #a79e76
url_style straight

input_delay 0
sync_to_monitor yes

